id: P007051
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25110
  title: ངེས་དོན་ཕྱག་རྒྱ་ཆེན་པོའི་སྒོམ་རིམ་གསལ་བར་བྱེད་པའི་ལེགས་བཤད་ཟླ་བའི་འོད་ཟེར།
  author: ''
  volumes:
    e80b3a515ac942c5b0175a387e1c063a:
      image_group_id: I1KG25112
      title: ''
      volume_number: 1
      total_pages: 538
ebook_metadata:
  title: ངེས་དོན་ཕྱག་རྒྱ་ཆེན་པོའི་སྒོམ་རིམ་གསལ་བར་བྱེད་པའི་ལེགས་བཤད་ཟླ་བའི་འོད་ཟེར།
  author: ''
  sku: P007051
  cover: cover.jpg
  layers:
  - pagination
